DROP TABLE IF EXISTS "reasoning";

CREATE TABLE "reasoning"
(
    "id"        INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    "statement"     TEXT CHARACTER utf8 NOT NULL,
    "query"    TEXT CHARACTER utf8 NOT NULL,
    "answer1" TEXT CHARACTER utf8 NOT NULL,
    "answer2"      TEXT CHARACTER utf8 NOT NULL,
    "correct_answer" TEXT CHARACTER utf8 NOT NULL
);
INSERT INTO "reasoning"
VALUES (NULL, 'Darek jest nie taki ciê¿ki jak Bogdan.', 'Kto jest ciê¿szy?', 'Bogdan', 'Darek', 'Bogdan'),
(NULL, 'Bartek jest wy¿szy ni¿ Antek.', 'Kto jest ni¿szy?', 'Antek', 'Bartek', 'Antek'),
(NULL, 'Filip jest nie tak smutny jak Bogdan.', 'Kto jest weselszy?', 'Filip', 'Bogdan', 'Filip'),
(NULL, 'Tomek jest l¿ejszy ni¿ Jan.', 'Kto jest ciê¿szy?', 'Jan', 'Tomek', 'Jan'),
(NULL, 'Witek jest g³upszy ni¿ Bolek.', 'Kto jest g³upszy?', 'Witek', 'Bolek', 'Witek'),
(NULL, 'Rafa³ jest nie tak ciê¿ki jak Roman.', 'Kto jest l¿ejszy?', 'Roman', 'Rafa³', 'Rafa³'),
(NULL, 'Bogdan jest nie tak szybki jak Krzyœ.', 'Kto jest wolniejszy?', 'Krzyœ', 'Bogdan', 'Bogdan'),
(NULL, 'Jacek jest l¿ejszy ni¿ Marcin.', 'Kto jest ciê¿szy?', 'Jacek', 'Marcin', 'Marcin'),
(NULL, 'Janusz jest m¹drzejszy ni¿ Eryk.', 'Kto jest m¹drzejszy.', 'Eryk', 'Janusz', 'Janusz'),
(NULL, 'Tomek jest weselszy ni¿ Marek.',  'Kto jest weselszy?', 'Marek', 'Tomek', 'Tomek'),
(NULL, 'Marcin jest wy¿szy ni¿ Jan.', 'Kto jest ni¿szy?', 'Marcin', 'Jan', 'Jan'),
(NULL, 'Julian jest l¿ejszy ni¿ Bartek.', 'Kto jest ciê¿szy?', 'Bartek', 'Julian', 'Julian'),
(NULL, 'Bogdan jest nie tak weso³y jak Janusz.', 'Kto jest weselszy?', 'Janusz', 'Bogdan', 'Bogdan'),
(NULL, 'Marcin jest m¹drzejszy ni¿ Pawe³.', 'Kto jest g³upszy?', 'Pawe³', 'Marcin', 'Pawe³'),
(NULL, 'Bolek jest wy¿szy ni¿ Adam.', 'Kto jest wy¿szy?', 'Adam', 'Bolek', 'Bolek'),
(NULL, 'Leon jest nie tak wolny jak Olek.', 'Kto jest wolniejszy?', 'Olek', 'Leon', 'Olek'),
(NULL, 'Bartek jest nie tak szybki jak Czarek.', 'Kto jest szybszy?', 'Czarek', 'Bartek', 'Czarek'),
(NULL, 'Jacek jest nie tak stary jak Stefan.', 'Kto jest starszy?', 'Jacek', 'Stefan', 'Stefan'),
(NULL, 'Bogdan jest wolniejszy ni¿ Janusz.', 'Kto jest wolniejszy?', 'Janusz', 'Bogdan', 'Bogdan'),
(NULL, 'Jacek jest nie tak wysoki jak Micha³.', 'Kto jest wy¿szy?', 'Micha³', 'Jacek', 'Micha³'),
(NULL, 'Janusz jest nie tak smutny jak Filip.', 'Kto jest smutniejszy?', 'Janusz', 'Filip', 'Filip'),
(NULL, 'Filip jest nie tak silny jak Czarek.', 'Kto jest silniejszy?', 'Czarek', 'Filip', 'Czarek'),
(NULL, 'Filip jest ciê¿szy ni¿ Eryk.', 'Kto jest ciê¿szy?', 'Eryk', 'Filip', 'Filip'),
(NULL, 'Bolek jest nie tak stary jak Karol.', 'Kto jest m³odszy?', 'Bolek', 'Karol', 'Bolek'),
(NULL, 'Julian jest nie tak m¹dry jak Marian.', 'Kto jest m¹drzejszy?', 'Marian', 'Julian', 'Marian'),
(NULL, 'Leon jest nie tak z³y jak Mirek.', 'Kto jest lepszy?', 'Leon', 'Mirek', 'Leon'),
(NULL, 'Karol jest nie tak stary jak Roman.', 'Kto jest starszy?', 'Roman', 'Karol', 'Roman'),
(NULL, 'Rafa³ jest lepszy ni¿ Adam.', 'Kto jest lepszy?', 'Rafa³', 'Adam', 'Rafa³'),
(NULL, 'Darek jest nie tak m³ody jak Czarek.', 'Kto jest m³odszy?', 'Czarek', 'Darek', 'Czarek'),
(NULL, 'Karol jest silniejszy ni¿ Rafa³.', 'Kto jest s³abszy?', 'Rafa³', 'Karol', 'Rafa³'),
(NULL, 'Bartek jest nie tak ciê¿ki jak Bogdan.', 'Kto jest ciê¿szy?', 'Bartek', 'Bogdan', 'Bogdan'),
(NULL, 'Filip jest nie tak z³y jak Czarek.', 'Kto jest gorszy?', 'Czarek', 'Bartek', 'Czarek'),
(NULL, 'Bolek jest wy¿szy ni¿ Marek.', 'Kto jest wy¿szy?', 'Marek', 'Bolek', 'Bolek'),
(NULL, 'Karol jest szybszy ni¿ Tomek.', 'Kto jest wolniejszy?', 'Karol', 'Tomek', 'Tomek'),
(NULL, 'Bogdan jest wy¿szy ni¿ Darek.', 'Kto jest ni¿szy?', 'Darek', 'Bogdan', 'Darek'),
(NULL, 'Julian jest nie tak m¹dry jak Mirek.', 'Kto jest m¹drzejszy?', 'Mirek', 'Julian', 'Mirek'),
(NULL, 'Jan jest gorszy ni¿ Julek.', 'Kto jest gorszy?', 'Jan', 'Julek', 'Jan'),
(NULL, 'Marian jest m³odszy ni¿ Czarek.', 'Kto jest m³odszy?', 'Czarek', 'Marian', 'Marian'),
(NULL, 'Bolek jest weselszy ni¿ Lech.', 'Kto jest weselszy?', 'Lech', 'Bolek', 'Bolek'),
(NULL, 'Janusz jest nie tak szybki jak Marcin.', 'Kto jest szybszy?', 'Janusz', 'Marcin', 'Marcin');

